### ISSUE TITLE
Compass and rotation

### ISSUE THREAD

**Issue by minhanh1234** [joseppii/PhylaxSensorControllerMK2#1]
Hi

Would you know if this chip can calculate compass angle like most magnetometer and would you have any example code to calculate rotation count? Example if i rotate the gyro on a table? (Example: 2 counter clockwise ration)

Thanks

**Comment by joseppii** [comment]
Hi,

I don't think the DMP inside the imu chip can do that. Check the link below,on section 4, it describes the built in functionality of the DMP : https://www.cdiweb.com/datasheets/invensense/application_note-programming_sequence_for_dmp_hw_functions_icm_20648.pdf
